---
    kind: pipeline
    type: docker
    name: default
    
    steps:
    - name: build
      image: golang:1.13
      commands:
      - go build

    - name: test
      image: golang:1.13
      commands:
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: coverage
      image: plugins/codecov
      settings:
#        token: f94217d3-9e6e-4fb7-b725-ff155c1b24bc
        files:
          - coverage.txt

    - name: publish
      image: plugins/docker
      settings:
        repo: docker.pkg.github.com/monkiato/apio-orchestrator-api/apio-orchestrator-api
        registry: docker.pkg.github.com
        tags: ${DRONE_TAG}
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
      when:
        event:
          - tag

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*